name: Deploy to Local VM

on:
  push:
    branches:
      - main  # ou le nom de ta branche

jobs:
  deploy:
    runs-on: self-hosted  # <--- TRES IMPORTANT : C'est ce qui appelle ta VM

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Run with Docker
        run: |
          # On arrête le projet actuel
          docker compose down --remove-orphans

          # PAR SÉCURITÉ : On s'assure que le conteneur parc_db est bien mort
          # Le "|| true" évite que le script s'arrête si le conteneur n'existe pas déjà
          docker rm -f parc_db || true

          # On relance proprement
          docker compose up -d --build
