name: Deploy to Local VM

on:
  push:
    branches:
      - main  # ou le nom de ta branche

jobs:
  deploy:
    runs-on: self-hosted  # <--- TRES IMPORTANT : C'est ce qui appelle ta VM

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Run with Docker
        run: |
          # Relance du deploy
          # 1. On arrete et on supprime les anciens conteneurs proprement
          docker compose down

          # 2. On lance la nouvelle version (build force la mise a jour)
          docker compose up -d --build
