name: Deploy to Local VM

on:
  push:
    branches:
      - main  # ou le nom de ta branche

jobs:
  deploy:
    runs-on: self-hosted  # <--- TRES IMPORTANT : C'est ce qui appelle ta VM

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Run with Docker
        run: |
          # Arrete tout et supprime meme les conteneurs "etrangers" au projet actuel
          docker compose down --remove-orphans

          # Relance proprement
          docker compose up -d --build
